Repository crmne/ruby_llm, pull requests merged in 2025-03, with the labels that each got.

#56 Improve accuracy of OpenAI capabilities `supports_vision?` and `supports_functions?` methods
  lib/ruby_llm/models.json
  lib/ruby_llm/models.rb
  lib/ruby_llm/providers/openai/capabilities.rb
  lib/tasks/models.rake
Labels: capabilities

#28 Fix tool `name` method to strip unsupported characters for OpenAI
  lib/ruby_llm/tool.rb
  spec/ruby_llm/tool_spec.rb
Labels: bug

#54 Add example about how to setup system messages in the Rails integration
  docs/guides/chat.md
  docs/guides/rails.md
Labels: documentation

#62 Support tools without params
  lib/ruby_llm/providers/gemini/tools.rb
  spec/fixtures/vcr_cassettes/chat_function_calling_claude-3-5-haiku-20241022_can_use_tools_without_parameters.yml
  spec/fixtures/vcr_cassettes/chat_function_calling_gemini-2_0-flash_can_use_tools_without_parameters.yml
  spec/fixtures/vcr_cassettes/chat_function_calling_gpt-4o-mini_can_use_tools_without_parameters.yml
  spec/ruby_llm/chat_tools_spec.rb
Labels: bug
