Repository crmne/ruby_llm, pull requests merged in 2025-07, with the labels that each got.

#255 Add JRuby to CI test job
  .github/workflows/cicd.yml
  Gemfile
  gemfiles/rails_7.1.gemfile
  gemfiles/rails_7.1.gemfile.lock
  spec/ruby_llm/chat_error_spec.rb
Labels: enhancement

#252 More details for configuring Ollama
  docs/configuration.md
Labels: documentation

#171 docs: add guide for using custom model names with acts_as helpers
  docs/guides/rails.md
Labels: documentation

#142 Support gpustack
  bin/console
  lib/ruby_llm.rb
  lib/ruby_llm/configuration.rb
  lib/ruby_llm/providers/gpustack.rb
  lib/ruby_llm/providers/gpustack/chat.rb
  lib/ruby_llm/providers/gpustack/models.rb
  spec/fixtures/vcr_cassettes/chat_basic_chat_functionality_gpustack_qwen3_can_handle_multi-turn_conversations.yml
  spec/fixtures/vcr_cassettes/chat_basic_chat_functionality_gpustack_qwen3_can_have_a_basic_conversation.yml
  spec/fixtures/vcr_cassettes/chat_basic_chat_functionality_gpustack_qwen3_replaces_previous_system_messages_when_replace_true.yml
  spec/fixtures/vcr_cassettes/chat_basic_chat_functionality_gpustack_qwen3_successfully_uses_the_system_prompt.yml
  spec/fixtures/vcr_cassettes/chat_function_calling_gpustack_qwen3_can_use_tools.yml
  spec/fixtures/vcr_cassettes/chat_function_calling_gpustack_qwen3_can_use_tools_in_multi-turn_conversations.yml
  spec/fixtures/vcr_cassettes/chat_function_calling_gpustack_qwen3_can_use_tools_with_multi-turn_streaming_conversations.yml
  spec/fixtures/vcr_cassettes/chat_function_calling_gpustack_qwen3_can_use_tools_without_parameters.yml
  spec/fixtures/vcr_cassettes/chat_function_calling_gpustack_qwen3_can_use_tools_without_parameters_in_multi-turn_streaming_conversations.yml
  spec/fixtures/vcr_cassettes/chat_streaming_responses_gpustack_qwen3_reports_consistent_token_counts_compared_to_non-streaming.yml
  spec/fixtures/vcr_cassettes/chat_streaming_responses_gpustack_qwen3_supports_streaming_responses.yml
  spec/fixtures/vcr_cassettes/chat_text_models_gpustack_qwen3_can_understand_remote_text.yml
  spec/fixtures/vcr_cassettes/chat_text_models_gpustack_qwen3_can_understand_text.yml
  spec/fixtures/vcr_cassettes/models_refresh_updates_models_and_returns_a_chainable_models_instance.yml
  spec/fixtures/vcr_cassettes/models_refresh_works_as_a_class_method_too.yml
  spec/ruby_llm/chat_error_spec.rb
  spec/spec_helper.rb
Labels: new provider

#241 Fix handling of multiple tool calls in single LLM response
  lib/ruby_llm/providers/anthropic/chat.rb
  lib/ruby_llm/providers/anthropic/tools.rb
  spec/fixtures/vcr_cassettes/chat_function_calling_anthropic_claude-3-5-haiku-20241022_can_handle_multiple_tool_calls_in_a_single_response.yml
  spec/fixtures/vcr_cassettes/chat_function_calling_bedrock_anthropic_claude-3-5-haiku-20241022-v1_0_can_handle_multiple_tool_calls_in_a_single_response.yml
  spec/fixtures/vcr_cassettes/chat_function_calling_deepseek_deepseek-chat_can_handle_multiple_tool_calls_in_a_single_response.yml
  spec/fixtures/vcr_cassettes/chat_function_calling_gemini_gemini-2_0-flash_can_handle_multiple_tool_calls_in_a_single_response.yml
  spec/fixtures/vcr_cassettes/chat_function_calling_openai_gpt-4_1-nano_can_handle_multiple_tool_calls_in_a_single_response.yml
  spec/fixtures/vcr_cassettes/chat_function_calling_openrouter_anthropic_claude-3_5-haiku_can_handle_multiple_tool_calls_in_a_single_response.yml
  spec/ruby_llm/chat_error_spec.rb
  spec/ruby_llm/chat_tools_spec.rb
  spec/ruby_llm/providers/anthropic/tools_spec.rb
Labels: bug

#75 Rails Generator for RubyLLM Models
  README.md
  docs/guides/rails.md
  docs/index.md
  lib/generators/ruby_llm/install/templates/INSTALL_INFO.md.tt
  lib/generators/ruby_llm/install/templates/chat_model.rb.tt
  lib/generators/ruby_llm/install/templates/create_chats_migration.rb.tt
  lib/generators/ruby_llm/install/templates/create_messages_migration.rb.tt
  lib/generators/ruby_llm/install/templates/create_tool_calls_migration.rb.tt
  lib/generators/ruby_llm/install/templates/initializer.rb.tt
  lib/generators/ruby_llm/install/templates/message_model.rb.tt
  lib/generators/ruby_llm/install/templates/tool_call_model.rb.tt
  lib/generators/ruby_llm/install_generator.rb
  lib/ruby_llm.rb
  lib/ruby_llm/railtie.rb
  spec/lib/generators/ruby_llm/install_generator_spec.rb
Labels: enhancement
